CREATE TABLE employe(
	id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
	salary INT(5) DEFAULT NULL,
    PRIMARY KEY (id)
)
CREATE DATABASE IF NOT EXISTS companydb;

INSERT INTO employe VALUES(
    (1, 'Jose', 1000)
)

SELECT * FROM employe WHERE id = 1;